#!/bin/bash

# Set app specific variables
app=$1
dbname=$app
dbuser=$app

# Load common variables and helpers
. ./_common.sh

# Source app helpers
. /usr/share/yunohost/apps/helpers

# Retrieve settings
domain=$(ynh_app_setting_get $app domain)

# Stop and remove the service
sudo systemctl -q stop mediagoblin-paster || true
sudo systemctl -q stop mediagoblin-celeryd || true
sudo systemctl -q disable mediagoblin-paster
sudo systemctl -q disable mediagoblin-celeryd
sudo yunohost service remove mediagoblin-paster
sudo yunohost service remove mediagoblin-celeryd
sudo rm -f /etc/systemd/system/mediagoblin-{paster,celeryd}.service

# Delete app directory and configurations
sudo rm -rf "/var/www/${app}"
[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Drop the database
exec_cmd "cd && dropdb ${dbname}" postgres
exec_cmd "cd && dropuser ${dbuser}" postgres

# Remove app dependencies and system user
ynh_package_autoremove "$DEPS_PKG_NAME" || true
sudo deluser --quiet --system mediagoblin

# Reload services
sudo systemctl daemon-reload
sudo service nginx reload || true
